Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -2,19 +2,11 @@ name: Upstream Sync
 
 permissions:
   contents: write
-  pull-requests: write
 
 on:
   schedule:
-    - cron: "15 2 * * *"
+    - cron: "15 2 * * *" # every day
   workflow_dispatch:
-    inputs:
-      upstream_branch:
-        description: "上游仓库分支名"
-        default: "main"
-      target_branch:
-        description: "目标分支名"
-        default: "main"
 
 jobs:
   sync_latest_from_upstream:
@@ -23,30 +15,26 @@ jobs:
     if: ${{ github.event.repository.fork }}
 
     steps:
+      # Step 1: run a standard checkout action
       - name: Checkout target repo
         uses: actions/checkout@v3
 
+      # Step 2: run the sync action
       - name: Sync upstream changes
         id: sync
         uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
         with:
-          upstream_sync_repo: cmliu/CF-Workers-SUB
-          upstream_sync_branch: ${{ github.event.inputs.upstream_branch || 'main' }}
-          target_sync_branch: ${{ github.event.inputs.target_branch || 'main' }}
-          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+          upstream_sync_repo: camel52zhang/huiji-cf
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
+
+          # Set test_mode true to run tests instead of the true action!!
           test_mode: false
 
-      - name: Handle conflicts
-        if: steps.sync.outcome == 'failure' && contains(steps.sync.output.message, 'conflict')
-        run: |
-          echo "冲突错误：请手动解决以下文件的冲突："
-          git diff --name-only --diff-filter=U
-          exit 1
-
-      - name: Notify failure
+      - name: Sync check
         if: failure()
-        uses: actions-slack/slack@v1
-        with:
-          status: failure
-        env:
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+        run: |
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md "
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          exit 1
